def Tag(resdicts):  # 回傳標籤
    Taglist = resdicts
    Taglist = [t for t in Taglist if "users入り" not in t]
    Taglist = [t.translate(str.maketrans(
        "", "", '"}{[]:<|>?/※\\⊂⊃*')) for t in Taglist]
    try:
        for i in range(0, len(Taglist)):
            lenth = len(Taglist[i])
            Taglist[i] = Taglist[i].replace('・', '_')
            Taglist[i] = Taglist[i].replace('.', '_')
            if lenth <= 5:
                Taglist[i] = Taglist[i].replace('ホロライブ', 'Hololive')
                Taglist[i] = Taglist[i].replace('レム', '雷姆')
                Taglist[i] = Taglist[i].replace('うちの子;', '')
                Taglist[i] = Taglist[i].replace('逆レイプ', '逆強暴')
                Taglist[i] = Taglist[i].replace('おもらし', '失禁')
                Taglist[i] = Taglist[i].replace('おっぱい', '歐派')
                Taglist[i] = Taglist[i].replace('手袋', '手套')
                Taglist[i] = Taglist[i].replace('触手', '觸手')
                Taglist[i] = Taglist[i].replace('駆逐艦', '驅逐艦')
                Taglist[i] = Taglist[i].replace('猫耳', '貓耳')
                Taglist[i] = Taglist[i].replace('裸体', '裸體')
                Taglist[i] = Taglist[i].replace('お尻', '臀部')
                Taglist[i] = Taglist[i].replace('腋', '腋下')
                Taglist[i] = Taglist[i].replace('猿轡', '口塞')
                Taglist[i] = Taglist[i].replace('おしっこ', '尿尿')
                Taglist[i] = Taglist[i].replace('首輪', '項圈')
                Taglist[i] = Taglist[i].replace('水着', '泳裝')
                Taglist[i] = Taglist[i].replace('ウマ娘', '賽馬娘')
                Taglist[i] = Taglist[i].replace('騎乗位', '騎乘位')
                Taglist[i] = Taglist[i].replace('立ち絵', '立繪')
                Taglist[i] = Taglist[i].replace('めぐみん', '惠惠')
                Taglist[i] = Taglist[i].replace('女の子', '女孩子')
                Taglist[i] = Taglist[i].replace('金髪', '金髮')
                Taglist[i] = Taglist[i].replace('鼠蹊部', '鼠蹊部')
                Taglist[i] = Taglist[i].replace('ロリ巨乳', '巨乳蘿莉')
                Taglist[i] = Taglist[i].replace('パイズリ', '乳交')
                Taglist[i] = Taglist[i].replace('悪堕ち', '黑化')
                Taglist[i] = Taglist[i].replace('妊娠', '懷孕')
                Taglist[i] = Taglist[i].replace('アヘ顔', '阿嘿顏')
            elif lenth > 5 and lenth <= 10:
                Taglist[i] = Taglist[i].replace('R-18.', 'R-18')
                Taglist[i] = Taglist[i].replace('Pokémon', '寶可夢')
                Taglist[i] = Taglist[i].replace('(百瀨莉緒)', '')
                Taglist[i] = Taglist[i].replace('(Fate))', ')')
                Taglist[i] = Taglist[i].replace('阿克婭(美好世界)', '阿克婭')
                Taglist[i] = Taglist[i].replace('(動物朋友))', ')')
                Taglist[i] = Taglist[i].replace('(sisters)', '')
                Taglist[i] = Taglist[i].replace('艦これ(艦C)', '艦C')
                Taglist[i] = Taglist[i].replace('(cervix)', '')
                Taglist[i] = Taglist[i].replace('(shore)', '')
                Taglist[i] = Taglist[i].replace('Fate GO', 'FGO ')
                Taglist[i] = Taglist[i].replace('サキュバス', '魅魔')
                Taglist[i] = Taglist[i].replace('乳首ピアス', '乳環')
                Taglist[i] = Taglist[i].replace('(otome)', '')

                Taglist[i] = Taglist[i].replace('魅惑のふともも', '魅惑的大腿')
                Taglist[i] = Taglist[i].replace('アークナイツ', '明日方舟')
            elif lenth > 10 and lenth < 20:
                Taglist[i] = Taglist[i].replace('バーチャルYouTuber', '虛擬YouTuber')
                Taglist[i] = Taglist[i].replace('宝多六花', '寶多六花')
                Taglist[i] = Taglist[i].replace('中二病でも恋がしたい!', '中二病也想談戀愛')
                Taglist[i] = Taglist[i].replace('ブラック_マジシャン_ガール', '黑魔導女孩')
                Taglist[i] = Taglist[i].replace('ご注文はうさぎですか', '請問您今天要來點兔子嗎')
                Taglist[i] = Taglist[i].replace('Рикка_Таканаш', '')
                Taglist[i] = Taglist[i].replace('ストライクウィッチーズ', '強襲魔女')
                Taglist[i] = Taglist[i].replace('ラバースーツ', '橡膠緊身衣')
                Taglist[i] = Taglist[i].replace('こよりすけっち', '')
            elif lenth >= 20:
                Taglist[i] = Taglist[i].replace('ミミ_ウリエ_フォン_シュヴァルツラング', '')
                Taglist[i] = Taglist[i].replace(
                    'カードファイト!!ヴァンガード', '卡片鬥爭!! 先導者')
                Taglist[i] = Taglist[i].replace('ヴァンガードご本人', '')
                Taglist[i] = Taglist[i].replace('九一式徹甲乳', '九一式徹甲乳')
                Taglist[i] = Taglist[i].replace(
                    '(KanColle late night one-hour drawing competition)', '')
                Taglist[i] = Taglist[i].replace(
                    '嫌な顔されながらおパンツ見せてもらいたいシリーズ', '擺出討厭的表情露出內褲')
                Taglist[i] = Taglist[i].replace('嫌パン', '嫌棄的表情')
                Taglist[i] = Taglist[i].replace('セーラームーンの必殺技', '必殺技')
                Taglist[i] = Taglist[i].replace(
                    '賽馬娘Pretty Derby いともたやすく行われるえげつない行為', '')
                Taglist[i] = Taglist[i].replace(
                    'ジーク(Fate Apocrypha)(Sieg (Fate Apocrypha))', '')
                Taglist[i] = Taglist[i].replace(
                    'The Idolmaster Cinderella Girls Starlight Stage', '')
                Taglist[i] = Taglist[i].replace(
                    'pants peeking from bloomers', '從燈籠褲裡偷看內褲')
                Taglist[i] = Taglist[i].replace('撫で回したい太もも', '讓人想狂摸一把的大腿')
                Taglist[i] = Taglist[i].replace(
                    '俺の股間がティロ_フィナーレ', '俺の股間がティロ_フィナーレ')
                Taglist[i] = Taglist[i].replace(
                    'イリヤスフィール_フォン_アインツベルン', '伊莉雅絲菲爾_馮_愛因茲貝倫')
                Taglist[i] = Taglist[i].replace(
                    'このおっぱいで聖女は無理でしょ', '聖女不可能有這種歐派吧')
                Taglist[i] = Taglist[i].replace('ご注文はうさぎですか', '請問您今天要來點兔子嗎？')
                Taglist[i] = Taglist[i].replace(
                    'フィッシュル_ヴォン_ルフシュロス_ナフィードット', '')
                Taglist[i] = Taglist[i].replace(
                    '絶対に働きたくないダンジョンマスターが惰眠をむさぼるまで', '')
                Taglist[i] = Taglist[i].replace(
                    '乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった…', '轉生成女性向遊戲只有毀滅END的壞人大小姐')
                Taglist[i] = Taglist[i].replace(
                    'ナスタシア_ニコラエヴナ_ロマノヴァ(Fate)', '安娜塔西亞_尼古拉耶芙娜_羅曼諾娃')
                Taglist[i] = Taglist[i].replace('このあと滅茶苦茶セックスした', '')
                Taglist[i] = Taglist[i].replace('モンスターハンターライズ', '魔物獵人崛起')
                Taglist[i] = Taglist[i].replace(
                    '伊莉雅絲菲爾_馮_愛因茲貝倫 Fate GrandOrder', '伊莉雅絲菲爾_馮_愛因茲貝倫')
                Taglist[i] = Taglist[i].replace(
                    'Nijigasaki High School School Idol Club', 'LoveLive！虹咲學園學園偶像同好會')
                Taglist[i] = Taglist[i].replace(
                    'ダーリン_イン_ザ_フランキス', 'Darling in the Franxx')
                Taglist[i] = Taglist[i].replace(
                    'アイドルマスターミリオンライブ!シアターデイズ', '偶像大師 百萬人演唱會 劇場時光')
                Taglist[i] = Taglist[i].replace(
                    '(Let Aim for the Deepest Part of the Otherworldly Labyrinth)', '')
                Taglist[i] = Taglist[i].replace('悪性隔絶魔境新宿(', '')
                Taglist[i] = Taglist[i].replace('魔法少女まどか★マギカ', '魔法少女小圓')
            Taglist[i] = Taglist[i].replace(':{"en":', '')
            Taglist[i] = Taglist[i].replace('{"tag":', '')
            Taglist[i] = Taglist[i].replace('うちの子;', '')
            Taglist[i] = Taglist[i].replace('ショートパンツ', '短褲')
            Taglist[i] = Taglist[i].replace('タイツ越しのパンツ', '透出絲襪的內褲')
            Taglist[i] = Taglist[i].replace('&amp;', '')
            Taglist[i] = Taglist[i].replace(' u0027s', '')
            Taglist[i] = Taglist[i].replace('translation', '')
            Taglist[i] = Taglist[i].replace('Miku must be an angel', 'Miku是天使')
            Taglist[i] = Taglist[i].replace('変身ヒロイン', '變身女主角')
            Taglist[i] = Taglist[i].replace('アイドルマスターシンデレラガールズ', '')
            Taglist[i] = Taglist[i].replace('Touhou Project ', '')
            Taglist[i] = Taglist[i].replace('ちっぱい', '貧乳')
            Taglist[i] = Taglist[i].replace('looks embarrassed', '羞恥')
            Taglist[i] = Taglist[i].replace('イリヤスフィール(プリズマ☆イリヤ)', '伊莉雅')
            Taglist[i] = Taglist[i].replace('Totooria Helmold', '托特莉亞·赫爾莫德')
            Taglist[i] = Taglist[i].replace('Atelier Meruru', '梅露露的鍊金工房')
            Taglist[i] = Taglist[i].replace('我々の業 界では御褒美です', '這在我們業界是一種獎勵')
            Taglist[i] = Taglist[i].replace('西木野真姫', '西木野真姬')
            Taglist[i] = Taglist[i].replace('国木田花丸', '國木田花丸')
            Taglist[i] = Taglist[i].replace('とある魔術の禁書目録', '魔法禁書目錄')
            Taglist[i] = Taglist[i].replace('緒方智絵里', '緒方智繪里')
            Taglist[i] = Taglist[i].replace('御坂美琴(御坂 美琴)v', '御坂美琴')
            Taglist[i] = Taglist[i].replace('少女前线', '少女前線')
            Taglist[i] = Taglist[i].replace('(Girls u0027 Frontline)', '')
            Taglist[i] = Taglist[i].replace(
                'panties through stockings', '隔著絲襪的內褲')
            Taglist[i] = Taglist[i].replace('ジャンヌ_ダルク', '聖女貞德')
            Taglist[i] = Taglist[i].replace('仰臥', '仰臥')
            Taglist[i] = Taglist[i].replace('手でハート', '(手比愛心)')
            Taglist[i] = Taglist[i].replace('乳内射精', '乳内射精')
            Taglist[i] = Taglist[i].replace(
                'ポートランド(アズールレーン)(Portland (Azur Lane))', '碧藍航線(波特蘭)')
            Taglist[i] = Taglist[i].replace('アズールレーン', '')
            Taglist[i] = Taglist[i].replace('バニースーツ', '兔子裝')
            Taglist[i] = Taglist[i].replace('催眠', '催眠')
            Taglist[i] = Taglist[i].replace('正常位', '正常位')
            Taglist[i] = Taglist[i].replace('提督LOVE(admiral love)', '提督LOVE')
            Taglist[i] = Taglist[i].replace('sailor mercury', '水野亞美')
            Taglist[i] = Taglist[i].replace('凌辱', '凌辱')
            Taglist[i] = Taglist[i].replace('夕立(Yuudachi)', '夕立')
            Taglist[i] = Taglist[i].replace('メルラン_プリズムリバー', '梅露蘭·普莉茲姆利巴')
            Taglist[i] = Taglist[i].replace('ルナサ_プリズムリバー', '露娜薩·普莉茲姆利巴')
            Taglist[i] = Taglist[i].replace('霧雨魔理沙', '霧雨魔理沙')
            Taglist[i] = Taglist[i].replace('リリカ_プリズムリバー', '露娜薩·普莉茲姆利巴')
            Taglist[i] = Taglist[i].replace('小説家になろう', '')
            Taglist[i] = Taglist[i].replace(' オーバーラップ文庫(Overlap Bunko)', '')
            Taglist[i] = Taglist[i].replace('破れストッキング', '破損的絲襪')
            Taglist[i] = Taglist[i].replace('long pink hair', '粉色長髮')
            Taglist[i] = Taglist[i].replace(
                'Kaguya-sama Love is War', '輝夜姬想讓人告白')
            Taglist[i] = Taglist[i].replace('全裸', '全裸')
            Taglist[i] = Taglist[i].replace('流し目', '斜視')
            Taglist[i] = Taglist[i].replace('Fate Grand Order ', 'FGO')
            Taglist[i] = Taglist[i].replace(
                'ちちしりふともも(boobs butt and thighs)', '')
            Taglist[i] = Taglist[i].replace(
                'Nijisanji Illustration Contest 2020)', '')
            Taglist[i] = Taglist[i].replace('Nijisanji', '彩虹社')
            Taglist[i] = Taglist[i].replace('白ビキニ', '白色比基尼')
            Taglist[i] = Taglist[i].replace('クリック推奨', '')
            Taglist[i] = Taglist[i].replace('cheerleader', '啦啦隊長')
            Taglist[i] = Taglist[i].replace(
                'Is the Order a Rabbit ', '請問您今天要來點兔子嗎')
            Taglist[i] = Taglist[i].replace('(little girl swimsuit)', '')
            Taglist[i] = Taglist[i].replace('胸囲の格差社会', '胸圍的格差社會')
            Taglist[i] = Taglist[i].replace('Virtual YouTuber', 'VTB')
            Taglist[i] = Taglist[i].replace('(Fate)(Kagetora Nagao (Fate)', '')
            Taglist[i] = Taglist[i].replace('笑撃のラスト', '')
            Taglist[i] = Taglist[i].replace('デカァァァァァいッ説明不要!!', '')
            Taglist[i] = Taglist[i].replace('魅惑のふともも', '魅惑的大腿')
            Taglist[i] = Taglist[i].replace('撫で回したい尻', '讓人想狂摸一把的屁股')
            Taglist[i] = Taglist[i].replace(
                'The Ryuo Work is Never Done!', '龍王的工作')
            Taglist[i] = Taglist[i].replace('玉藻の前', '玉藻前')
            Taglist[i] = Taglist[i].replace(
                'まったく、駆逐艦は最高だぜ!!(驅逐艦真的太棒了！)', '驅逐艦真的太棒了!')
            Taglist[i] = Taglist[i].replace('Uma Musume Pretty Derby', '賽馬娘')
            Taglist[i] = Taglist[i].replace('ウマ娘プリティーダービー', '賽馬娘Pretty Derby')
            Taglist[i] = Taglist[i].replace('Genshin Impact', '原神')
            Taglist[i] = Taglist[i].replace('あなたちゃん(Anata-chan)', '高咲侑')
            Taglist[i] = Taglist[i].replace(' Fate GrandOrder Fate ポケモン ', '')
            Taglist[i] = Taglist[i].replace('クロスオーバー', '')
            Taglist[i] = Taglist[i].replace('Granblue Fantasy ', '碧藍幻想')
            Taglist[i] = Taglist[i].replace('みしだきたい乳', '令人想大揉特揉的奶')
            Taglist[i] = Taglist[i].replace('02(Darling in the Franxx)', '')
            Taglist[i] = Taglist[i].replace('DARLINGintheFRANXX', '')
            Taglist[i] = Taglist[i].replace('オリジナル', '原創')
            Taglist[i] = Taglist[i].replace('全てはここから始まった', '初始')
            Taglist[i] = Taglist[i].replace(
                'Saekano How to Raise a Boring Girlfriend', '不起眼女主角培育法')
            Taglist[i] = Taglist[i].replace(
                'How to Raise a Boring Girlfriend', '不起眼女主角培育法')
            Taglist[i] = Taglist[i].replace('冴えない彼女の育てかた(不起眼女主角培育法)', '')
            Taglist[i] = Taglist[i].replace('桜内梨子', '櫻内梨子')
            Taglist[i] = Taglist[i].replace('ラブライブ!サンシャイン!!', '')
            Taglist[i] = Taglist[i].replace('Girls und Panzer', '少女與戰車')
            Taglist[i] = Taglist[i].replace('なにこれかわいい', '這是什麼好可愛')
            Taglist[i] = Taglist[i].replace('バレンタイン', '情人節')
            Taglist[i] = Taglist[i].replace('カンナカムイ', '康娜卡姆依')
            Taglist[i] = Taglist[i].replace('小林さんちのメイドラゴン', '小林家的龍女僕')
            Taglist[i] = Taglist[i].replace('crossover', '混合')
            Taglist[i] = Taglist[i].replace('フランドール_スカーレット', '')
            Taglist[i] = Taglist[i].replace('一之瀬アスナ(バニーガール)', '一之瀨亞絲娜(兔女郎)')
            Taglist[i] = Taglist[i].replace('Blue Archive', '蔚藍檔案')
            Taglist[i] = Taglist[i].replace(
                '俺の主砲が一斉掃射(My main batteries are all firing a salvo!)', '')
            Taglist[i] = Taglist[i].replace(
                '提督LOVE 俺の主砲が一斉掃射 愛のあるセックス ハメ撮り', '')
            Taglist[i] = Taglist[i].replace('即夜戦(即夜戰)', '即夜戰')
            Taglist[i] = Taglist[i].replace(
                '前から見えるお尻(butt visible from the front)', '')
            Taglist[i] = Taglist[i].replace('挟まれたい谷間 魅惑の谷間 艦ぱい', '')
            Taglist[i] = Taglist[i].replace('jumpsuit', '連身衣')
            Taglist[i] = Taglist[i].replace('Pokemon trainer', '寶可夢訓練家')
            Taglist[i] = Taglist[i].replace(
                'Female Trainer (Pokemon GO)', '女寶可夢訓練家')
            Taglist[i] = Taglist[i].replace('Prisma Illya', '魔法少女伊莉亞')
            Taglist[i] = Taglist[i].replace('Altria Alter', '')
            Taglist[i] = Taglist[i].replace(' 二代目はオルタちゃん〜2016クリスマス〜', '')
            Taglist[i] = Taglist[i].replace('クロエ_フォン_アインツベルン', '克洛伊_馮_愛因茲貝倫')
            Taglist[i] = Taglist[i].replace('(Fate)(Ibaraki Doji (Fate))', '')
            Taglist[i] = Taglist[i].replace('聖女貞德_オルタ_サンタ_リリィ', '聖誕幼貞')
            Taglist[i] = Taglist[i].replace('オーバーラップ文庫(Overlap Bunko)', '')
            Taglist[i] = Taglist[i].replace('沖田総司 エレナ_ブラヴァツキー', '')
            Taglist[i] = Taglist[i].replace('(Fate)(Nero Claudius (Fate))', '')
            Taglist[i] = Taglist[i].replace(
                '美遊_エーデルフェルト(美遊‧艾蒂菲爾特) Fate GrandOrder FGO', '美遊‧艾蒂菲爾特')
            Taglist[i] = Taglist[i].replace('エレナ_ブラヴァツキー(Fate)', '海倫娜·布拉瓦茨基')
            Taglist[i] = Taglist[i].replace('魔法少女紀行_〜プリズマ_コーズ〜', '')
            Taglist[i] = Taglist[i].replace(
                'アイドルマスターミリオンライブ!(偶像大師 百萬人演唱會！)', '偶像大師 百萬人演唱會')
            Taglist[i] = Taglist[i].replace(
                '艦隊これくしょん(艦隊Collection)', '艦隊Collection')
            Taglist[i] = Taglist[i].replace('ワンサイドアップ(one side up)', '')
            Taglist[i] = Taglist[i].replace('CLIPSTUDIOPAINT', '')
            Taglist[i] = Taglist[i].replace('この素晴らしい世界に祝福を!', '為美好的世界獻上祝福')
            Taglist[i] = Taglist[i].replace('戦姫絶唱シンフォギア', '戰姬絕唱SYMPHOGEAR')
            Taglist[i] = Taglist[i].replace('ごちうさマイクロビキニ部', '')
            Taglist[i] = Taglist[i].replace('超\x08平和バスターズ', '')
            Taglist[i] = Taglist[i].replace('Prisma Illya ', '伊莉亞')
            Taglist[i] = Taglist[i].replace('パンツはかぶるもの', '內褲戴在頭上')
            Taglist[i] = Taglist[i].replace(' 二代目はオルタちゃん〜2016クリスマス〜', '')
            Taglist[i] = Taglist[i].replace('(Fate)(Ibaraki Doji (Fate))', '')
            Taglist[i] = Taglist[i].replace('クロエ_フォン_アインツベルン', '克洛伊_馮_愛因茲貝倫')
            Taglist[i] = Taglist[i].replace('CLIPSTUDIOPAINT', '')
            Taglist[i] = Taglist[i].replace(
                '艦隊これくしょん(艦隊Collection)', '艦隊Collection')
            Taglist[i] = Taglist[i].replace(
                '(Saratoga (Kantai Collection))', '')
            Taglist[i] = Taglist[i].replace('艦ぱい', '艦乳')
            Taglist[i] = Taglist[i].replace('美遊_エーデルフェルト', '美遊‧艾蒂菲爾特')
            Taglist[i] = Taglist[i].replace('海倫娜·布拉瓦茨基(Fate)', '海倫娜·布拉瓦茨基')
            Taglist[i] = Taglist[i].replace(
                'イドルマスターミリオンライブ!(偶像大師 百萬人演唱會！)', '偶像大師 百萬人演唱會')
            Taglist[i] = Taglist[i].replace('CLIPSTUDIOPAINT', '')
            Taglist[i] = Taglist[i].replace('ガールズパンツァー', '少女與戰車')
            Taglist[i] = Taglist[i].replace('女子大生', '女大生')
            Taglist[i] = Taglist[i].replace('ネルケと伝説の錬金術士たち', '奈爾克與傳說之鍊金術士們')
            Taglist[i] = Taglist[i].replace('アトリエシリーズ(鍊金術士系列)', '鍊金術士系列')
            Taglist[i] = Taglist[i].replace('Oozora Subaru', '大空昴')
            Taglist[i] = Taglist[i].replace(
                'Female Protagonist(Sword Shield)', '')
            Taglist[i] = Taglist[i].replace('女主人公(剣盾)', '')
            Taglist[i] = Taglist[i].replace('ジャンパースカート', '吊帶裙')
            Taglist[i] = Taglist[i].replace(
                '(ウマ娘)(Super Creek (Uma Musume))', '')
            Taglist[i] = Taglist[i].replace(
                '(ウマ娘)(Mihono Bourbon (Uma Musume))', '')
            Taglist[i] = Taglist[i].replace(
                '(ウマ娘)(Satono Diamond (Uma Musume))', '')
            Taglist[i] = Taglist[i].replace(
                '(ウマ娘)(Kitasan Black (Uma Musume))', '')
            Taglist[i] = Taglist[i].replace('(ウマ娘)(Mejiro McQueen (UMPD))', '')
            Taglist[i] = Taglist[i].replace('(cervix)', '')
            Taglist[i] = Taglist[i].replace('(プリコネ)(', '(')
            Taglist[i] = Taglist[i].replace(
                'プリンセスコネクト!ReDive', '超異域公主連結 ReDive')
            Taglist[i] = Taglist[i].replace('(Princess Connect!', '公主連結')
            Taglist[i] = Taglist[i].replace('スヤリス姫', '栖夜公主')
            Taglist[i] = Taglist[i].replace(
                '全裸(ヌード)(birth奶) 胸合わせ(胸部互day suit)', '')
            Taglist[i] = Taglist[i].replace(
                'ネルケと伝説の錬金術士たち(Nelke the Legendary Alchemists)', '奈爾克與傳說之鍊金術士們')
            Taglist[i] = Taglist[i].replace('ブルマ', '燈籠褲')
            Taglist[i] = Taglist[i].replace('全裸(ヌード)(birthday suit)', '')
            Taglist[i] = Taglist[i].replace('Princess Connect!', '公主連結')
            Taglist[i] = Taglist[i].replace('新条アカネ', '新條茜')
            Taglist[i] = Taglist[i].replace('プリンツ_オイゲン', '歐根親王')
            Taglist[i] = Taglist[i].replace('アルトリア_ペンドラゴン', '阿爾托莉雅·潘德拉貢')
            Taglist[i] = Taglist[i].replace('bunny suit)', '(兔子裝)')
            Taglist[i] = Taglist[i].replace('愛のあるセックス', '有愛的性')
            Taglist[i] = Taglist[i].replace('スーパーダンガンロンパ2 ', '')
            Taglist[i] = Taglist[i].replace('white sailor uniform', '白色學生制服')
            Taglist[i] = Taglist[i].replace('long white hair', '白色長髮')
            Taglist[i] = Taglist[i].replace(
                'ミリシタ(Million Live! Theater Days)', '')
            Taglist[i] = Taglist[i].replace(
                '白ニーソ(white knee-high socks)', '白色過膝襪')
            Taglist[i] = Taglist[i].replace('プリティウェイトレス', '')
            Taglist[i] = Taglist[i].replace('(Fate)(Nemo )', '')
            Taglist[i] = Taglist[i].replace(
                'ライネス_エルメロイ_アーチゾルテ', '萊妮絲·埃爾梅羅·阿奇佐爾緹')
            Taglist[i] = Taglist[i].replace('(FGOIllustration Contest 3)', '')
            Taglist[i] = Taglist[i].replace('カムイ(FEif)', '神威')
            Taglist[i] = Taglist[i].replace('はいてない', '沒穿內褲')
            Taglist[i] = Taglist[i].replace('ドールズフロントライン(少女前線)', '少女前線')
            Taglist[i] = Taglist[i].replace('Girls Frontline', '少前')
            Taglist[i] = Taglist[i].replace('グリッドマンの下半身担当', '')
            Taglist[i] = Taglist[i].replace('源頼光(水着)', '源賴光(泳裝)')
            Taglist[i] = Taglist[i].replace(
                'K2(ドールズフロントライン)(K2(少女前線))', 'K2(少女前線)')
            Taglist[i] = Taglist[i].replace('ールズフロントライン', '少女前線')
            Taglist[i] = Taglist[i].replace('魅惑の谷間', '魅惑的乳溝')
            Taglist[i] = Taglist[i].replace('usersタグ整理推奨', '')
            Taglist[i] = Taglist[i].replace('エミリア(リゼロ)', '愛蜜莉雅')
            Taglist[i] = Taglist[i].replace('ラム(リゼロ)', '拉姆')
            Taglist[i] = Taglist[i].replace('ネロ_クラウディウス(水着)', '尼祿·克勞狄烏斯(泳裝)')
            Taglist[i] = Taglist[i].replace('ご注文はスク水ですか', '')
            Taglist[i] = Taglist[i].replace('ランジェリー', '女性內衣')
            Taglist[i] = Taglist[i].replace('前川みく', '前川未來')
            Taglist[i] = Taglist[i].replace('(偶像大師 灰姑娘女孩)', '偶像大師 灰姑娘女孩')
            Taglist[i] = Taglist[i].replace('童貞を殺すセーター', '童貞殺毛衣')
            Taglist[i] = Taglist[i].replace('ロングブーツ', '長筒靴')
            Taglist[i] = Taglist[i].replace('レム(リゼロ)', '雷姆')
            Taglist[i] = Taglist[i].replace('ハイレグスーツ', '高腿緊身連衣褲')
            Taglist[i] = Taglist[i].replace('ハイレグレオタード', '高胸緊身衣')
            Taglist[i] = Taglist[i].replace('青髪ロング', '藍色長髮')
            Taglist[i] = Taglist[i].replace('オリジナル', '')
            Taglist[i] = Taglist[i].replace('守りたい、この笑顔', '')
            Taglist[i] = Taglist[i].replace('ウマ娘プリティーダービー', '賽馬娘')
            Taglist[i] = Taglist[i].replace('Girls Frontline', '')
            Taglist[i] = Taglist[i].replace('少女前線', '')
            Taglist[i] = Taglist[i].replace(
                '(Dolls Frontier illustration contest)', '')
            Taglist[i] = Taglist[i].replace('(ドールズフロントライン)', '')
            Taglist[i] = Taglist[i].replace('スケアクロウ(ドールズフロントライン)', '稻草人')
            Taglist[i] = Taglist[i].replace('ウロボロス(ドールズフロントライン)', '銜尾蛇')
            Taglist[i] = Taglist[i].replace('ドリーマー(ドールズフロントライン)', '夢想家')
            Taglist[i] = Taglist[i].replace('ワシミミズク(けものフレンズ)', '雕鴞(動物朋友)')
            Taglist[i] = Taglist[i].replace('(けものフレンズ)(', '(')
            Taglist[i] = Taglist[i].replace(
                'My Next Life as a Villainess All Routes Lead to Doom!', '轉生成女性向遊戲只有毀滅END的壞人大小姐')
            Taglist[i] = Taglist[i].replace('ショートヘア', '短髮')
            Taglist[i] = Taglist[i].replace('ライン入りソックス', '條紋襪')
            Taglist[i] = Taglist[i].replace('マイクロミニ', '極短裙')
            Taglist[i] = Taglist[i].replace('フランケンシュタイン', '科學怪人')
            Taglist[i] = Taglist[i].replace('またデジタル殿が死んでおられるぞ', '')
            Taglist[i] = Taglist[i].replace('間接キス', '間接接吻')
            Taglist[i] = Taglist[i].replace('Raiden Shogun', '雷電將軍')
            Taglist[i] = Taglist[i].replace('天々座理世', '天天座理世')
            Taglist[i] = Taglist[i].replace('静凛', '静凛')
            Taglist[i] = Taglist[i].replace(
                '大和 武蔵 長門 高雄型 愛宕 摩耶 鳥海 妙高 羽黒 能代', '')
            Taglist[i] = Taglist[i].replace(
                '熊野 利根型 筑摩 矢矧 雪風 浦風 磯風 浜風 野分 清霜 那智 足柄 阿武隈 曙 潮 霞 不知火 青葉 鬼怒 浦波', '')

            # Taglist[i]= translator.translate(Taglist[i], dest='zh-tw').text
        # print(Taglist)
        return Taglist
    except Exception as err:
        print(err)
